# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    param_fetcher_listener: force
    exception:
      exception_controller: 'fos_rest.exception.controller:showAction'
      codes:
        App\Services\Spotify\Exception\CannotRetrieveSpotifyList: 400
    format_listener:
      rules:
        - { path: ^/, prefer_extension: false, fallback_format: json, priorities: [ json ] }